# Generated by Django 5.0.2 on 2024-04-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_Name', models.CharField(max_length=20)),
                ('F_Designation', models.CharField(max_length=20)),
                ('Subject', models.CharField(max_length=20)),
                ('Department', models.CharField(max_length=20)),
                ('Educational_Qualification', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Specialization', models.CharField(max_length=20)),
                ('Field_of_Interest', models.CharField(max_length=20)),
                ('Teaching_Experience', models.IntegerField()),
            ],
        ),
    ]
